In [85]:
import pandas as pd
import numpy as np

In [86]:
# load dataset
df = pd.read_csv("DateFruit_Dataset.csv")

In [87]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [88]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [89]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [90]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
le = LabelEncoder()
y = le.fit_transform(y)

In [91]:
# train test split and scale our data
from sklearn.model_selection import train_test_split


X_train , X_test , y_train , y_test  = train_test_split(
    X , y , test_size=0.2 , random_state=42)

In [92]:
X_train.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092

In [93]:
# Scale our data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [94]:
# Build Our KNN Model
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [95]:
# Convert into tensor
X_train_tensor = torch.tensor(X_train_scaled , dtype=torch.float32)
y_train_tensor = torch.tensor(y_train , dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled , dtype=torch.float32)
y_test_tensor = torch.tensor(y_test , dtype=torch.long)

In [96]:
# use TeansorDataset for data loding
train_dataset = TensorDataset(X_train_tensor , y_train_tensor)
test_dataset = TensorDataset(X_test_tensor , y_test_tensor)

In [97]:
# Add Dataloader 

train_loader = DataLoader(train_dataset , batch_size=32 , shuffle=True)
test_loader = DataLoader(test_dataset , batch_size=32)

In [98]:
# Build Our Model
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),

            nn.Linear(64 , 64),
            nn.ReLU(),

            nn.Linear(64, 7)
        )
        
    def forward(self , x):
        return self.model(x)

In [99]:
# Calculate and optim
model = ANN()
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [100]:

# Training Our model 
epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb , yb in train_loader:
        optimizer.zero_grad()
        outputs = model(xb)
        loss = criteria(outputs , yb)
        loss.backward()

        optimizer.step() # update params
        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)
    print(f"epoch {epoch+1} / {epochs} , loss : {train_loss} ")

epoch 1 / 100 , loss : 1.7042639307353808
epoch 2 / 100 , loss : 1.1573224456413933
epoch 3 / 100 , loss : 0.7577693112518477
epoch 4 / 100 , loss : 0.571910032759542
epoch 5 / 100 , loss : 0.46900537933992303
epoch 6 / 100 , loss : 0.40117852713750757
epoch 7 / 100 , loss : 0.35322345015795337
epoch 8 / 100 , loss : 0.3118778412108836
epoch 9 / 100 , loss : 0.2835752989934838
epoch 10 / 100 , loss : 0.2641408981188484
epoch 11 / 100 , loss : 0.25090970714455063
epoch 12 / 100 , loss : 0.2448890649754068
epoch 13 / 100 , loss : 0.21933689551508945
epoch 14 / 100 , loss : 0.21153057593366373
epoch 15 / 100 , loss : 0.20405649069858633
epoch 16 / 100 , loss : 0.19491975041835205
epoch 17 / 100 , loss : 0.1859288293382396
epoch 18 / 100 , loss : 0.18302729758231537
epoch 19 / 100 , loss : 0.18052396631759146
epoch 20 / 100 , loss : 0.1758369064849356
epoch 21 / 100 , loss : 0.16205453095228775
epoch 22 / 100 , loss : 0.1627873668204183
epoch 23 / 100 , loss : 0.1633457943149235
epoch 24 / 100 , loss : 0.15023647362123366
epoch 25 / 100 , loss : 0.14384697102334187
epoch 26 / 100 , loss : 0.14384692972121033
epoch 27 / 100 , loss : 0.14710164547938367
epoch 28 / 100 , loss : 0.14821858121001202
epoch 29 / 100 , loss : 0.1336035206913948
epoch 30 / 100 , loss : 0.13252226603419884
epoch 31 / 100 , loss : 0.12797682991494302
epoch 32 / 100 , loss : 0.12337907841024191
epoch 33 / 100 , loss : 0.11790255068436913
epoch 34 / 100 , loss : 0.11348040661086208
epoch 35 / 100 , loss : 0.11273178490607635
epoch 36 / 100 , loss : 0.12033407017588615
epoch 37 / 100 , loss : 0.12191271360801614
epoch 38 / 100 , loss : 0.11679227646116329
epoch 39 / 100 , loss : 0.10576868057250977
epoch 40 / 100 , loss : 0.10105023808453394
epoch 41 / 100 , loss : 0.10223202358769334
epoch 42 / 100 , loss : 0.09538311705641124
epoch 43 / 100 , loss : 0.09201945882776509
epoch 44 / 100 , loss : 0.09083318499767262
epoch 45 / 100 , loss : 0.09124539152759573
epoch 46 / 100 , loss : 0.0870133145995762
epoch 47 / 100 , loss : 0.08829939729817536
epoch 48 / 100 , loss : 0.0872200917776512
epoch 49 / 100 , loss : 0.08548946549063144
epoch 50 / 100 , loss : 0.08173307072897644
epoch 51 / 100 , loss : 0.0786456277836924
epoch 52 / 100 , loss : 0.0769655753089034
epoch 53 / 100 , loss : 0.07419458709900147
epoch 54 / 100 , loss : 0.07366505815930989
epoch 55 / 100 , loss : 0.07262309693285952
epoch 56 / 100 , loss : 0.07283119590062162
epoch 57 / 100 , loss : 0.07445431346802608
epoch 58 / 100 , loss : 0.06603773430992
epoch 59 / 100 , loss : 0.06660892692920954
epoch 60 / 100 , loss : 0.06265852964766648
epoch 61 / 100 , loss : 0.06112107367295286
epoch 62 / 100 , loss : 0.0625405923017989
epoch 63 / 100 , loss : 0.0684923320684744
epoch 64 / 100 , loss : 0.05667493378986483
epoch 65 / 100 , loss : 0.056388706211810524
epoch 66 / 100 , loss : 0.05744779648502236
epoch 67 / 100 , loss : 0.05413354896818814
epoch 68 / 100 , loss : 0.05827227360366479
epoch 69 / 100 , loss : 0.05437499916423922
epoch 70 / 100 , loss : 0.052040294177182346
epoch 71 / 100 , loss : 0.04907171039477638
epoch 72 / 100 , loss : 0.04947099478348442
epoch 73 / 100 , loss : 0.048718708185175354
epoch 74 / 100 , loss : 0.04743768122938016
epoch 75 / 100 , loss : 0.048719829596255135
epoch 76 / 100 , loss : 0.04802426315196182
epoch 77 / 100 , loss : 0.04599611473310253
epoch 78 / 100 , loss : 0.0436917312807687
epoch 79 / 100 , loss : 0.04376515019280107
epoch 80 / 100 , loss : 0.04518663640255514
epoch 81 / 100 , loss : 0.04052649620596482
epoch 82 / 100 , loss : 0.039586677762639265
epoch 83 / 100 , loss : 0.0379973573245756
epoch 84 / 100 , loss : 0.038915682543555034
epoch 85 / 100 , loss : 0.03626514432202701
epoch 86 / 100 , loss : 0.03820330714401991
epoch 87 / 100 , loss : 0.03438204996611761
epoch 88 / 100 , loss : 0.03619659449095312
epoch 89 / 100 , loss : 0.031720864586532116
epoch 90 / 100 , loss : 0.03175308288115522
epoch 91 / 100 , loss : 0.03081534991202795
epoch 92 / 100 , loss : 0.031579986072914755
epoch 93 / 100 , loss : 0.03215804439969361
epoch 94 / 100 , loss : 0.027906643287481173
epoch 95 / 100 , loss : 0.02894062192543693
epoch 96 / 100 , loss : 0.029461936458297398
epoch 97 / 100 , loss : 0.031026219635311027
epoch 98 / 100 , loss : 0.027544480728228456
epoch 99 / 100 , loss : 0.029454750535280808
epoch 100 / 100 , loss : 0.02599538757931441

In [104]:
# Evealuation our model
model.eval()
total = 0
correct = 0

with torch.no_grad():
    for xb , yb in test_loader:
        outputs = model(xb) # [0.2 , 1.2 , -1.2]...7Val
        _ , predicated = torch.max(outputs , 1) # max or max index return

        correct += (predicated == yb).sum().item()
        total += yb.size(0) # Actual Sample in each batch


print("Accuracy :", correct / total)

Accuracy : 0.9444444444444444

In [106]:
print("Accuracy :", total)
print("Accuracy :", correct )

Accuracy : 180
Accuracy : 170